export interface PanelDatabaseEntry {
  id: string;
  brand: string;
  model: string;
  cellType: 'mono-perc' | 'n-type' | 'hjt' | 'topcon' | 'bifacial';
  power: number;
  voc: number;
  vmp: number;
  isc: number;
  imp: number;
  tempCoeffVoc: number;
  tempCoeffIsc: number;
  tempCoeffPmax: number;
  noct: number;
  efficiency: number;
  cells: number;
  cellSize: number;
  dimensions: { width: number; height: number };
  weight: number;
  seriesFuseRating: number;
  maxSystemVoltage: number;
  frameColor: string;
  backsheetColor: string;
  certifications: string[];
  warrantyPerformance: number;
  warrantyProduct: number;
  degradationYear1: number;
  degradationYear25: number;
  availableInYemen: boolean;
  yemenDistributor?: string;
  enabled: boolean;
}

export const yemenPanels: PanelDatabaseEntry[] = [
  // ============================================================
  // JINKO SOLAR - Tiger Neo Series (N-type TOPCon)
  // ============================================================
  {
    id: 'jinko-tiger-neo-445n',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM445N-54HL4-V',
    cellType: 'topcon',
    power: 445,
    voc: 42.10,
    vmp: 35.20,
    isc: 13.58,
    imp: 12.64,
    tempCoeffVoc: -0.26,
    tempCoeffIsc: 0.038,
    tempCoeffPmax: -0.29,
    noct: 42,
    efficiency: 21.88,
    cells: 120,
    cellSize: 182,
    dimensions: { width: 1134, height: 1722 },
    weight: 21.8,
    seriesFuseRating: 20,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'jinko-tiger-neo-575n',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM575N-72HL4-V',
    cellType: 'topcon',
    power: 575,
    voc: 52.20,
    vmp: 44.10,
    isc: 14.10,
    imp: 13.04,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.037,
    tempCoeffPmax: -0.28,
    noct: 43,
    efficiency: 22.24,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 28.6,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'jinko-tiger-neo-635n',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM635N-72HL4-V',
    cellType: 'topcon',
    power: 635,
    voc: 54.10,
    vmp: 46.20,
    isc: 14.75,
    imp: 13.75,
    tempCoeffVoc: -0.24,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.27,
    noct: 44,
    efficiency: 23.47,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'jinko-tiger-neo-685n',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM685N-78HL4-V',
    cellType: 'topcon',
    power: 685,
    voc: 55.80,
    vmp: 47.80,
    isc: 15.30,
    imp: 14.33,
    tempCoeffVoc: -0.24,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.26,
    noct: 45,
    efficiency: 24.12,
    cells: 156,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 32.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // LONGi SOLAR - Hi-MO Series
  // ============================================================
  {
    id: 'longi-himo7-450',
    brand: 'LONGi Solar',
    model: 'Hi-MO 7 LR5-54HTH-450',
    cellType: 'topcon',
    power: 450,
    voc: 42.50,
    vmp: 35.60,
    isc: 13.38,
    imp: 12.64,
    tempCoeffVoc: -0.255,
    tempCoeffIsc: 0.037,
    tempCoeffPmax: -0.29,
    noct: 43,
    efficiency: 22.13,
    cells: 108,
    cellSize: 182,
    dimensions: { width: 1134, height: 1722 },
    weight: 21.5,
    seriesFuseRating: 20,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Yemen Sun Energy Trading',
    enabled: true,
  },
  {
    id: 'longi-himo6-580',
    brand: 'LONGi Solar',
    model: 'Hi-MO 6 LR5-72HBD-580',
    cellType: 'mono-perc',
    power: 580,
    voc: 50.60,
    vmp: 43.00,
    isc: 14.68,
    imp: 13.49,
    tempCoeffVoc: -0.260,
    tempCoeffIsc: 0.040,
    tempCoeffPmax: -0.30,
    noct: 44,
    efficiency: 21.62,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 28.6,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 25,
    warrantyProduct: 12,
    degradationYear1: 2.0,
    degradationYear25: 5.0,
    availableInYemen: true,
    yemenDistributor: 'Yemen Sun Energy Trading',
    enabled: true,
  },
  {
    id: 'longi-himo9-660',
    brand: 'LONGi Solar',
    model: 'Hi-MO 9 LR6-72BDH-660',
    cellType: 'topcon',
    power: 660,
    voc: 54.50,
    vmp: 47.00,
    isc: 14.90,
    imp: 14.04,
    tempCoeffVoc: -0.245,
    tempCoeffIsc: 0.035,
    tempCoeffPmax: -0.27,
    noct: 44,
    efficiency: 24.02,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Yemen Sun Energy Trading',
    enabled: true,
  },
  {
    id: 'longi-himo9-675',
    brand: 'LONGi Solar',
    model: 'Hi-MO 9 LR7-72HBD-675',
    cellType: 'topcon',
    power: 675,
    voc: 55.20,
    vmp: 47.60,
    isc: 15.05,
    imp: 14.18,
    tempCoeffVoc: -0.240,
    tempCoeffIsc: 0.035,
    tempCoeffPmax: -0.26,
    noct: 44,
    efficiency: 24.55,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Yemen Sun Energy Trading',
    enabled: true,
  },

  // ============================================================
  // TRINA SOLAR - Vertex Series
  // ============================================================
  {
    id: 'trina-vertex-s-450',
    brand: 'Trina Solar',
    model: 'Vertex S+ TSM-450DEG19RC.20',
    cellType: 'topcon',
    power: 450,
    voc: 42.20,
    vmp: 35.40,
    isc: 13.48,
    imp: 12.71,
    tempCoeffVoc: -0.255,
    tempCoeffIsc: 0.038,
    tempCoeffPmax: -0.29,
    noct: 42,
    efficiency: 22.15,
    cells: 120,
    cellSize: 182,
    dimensions: { width: 1134, height: 1722 },
    weight: 21.8,
    seriesFuseRating: 20,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE', 'PID'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Gulf Solar Technologies',
    enabled: true,
  },
  {
    id: 'trina-vertex-n-580',
    brand: 'Trina Solar',
    model: 'Vertex N TSM-580DE21M',
    cellType: 'topcon',
    power: 580,
    voc: 52.30,
    vmp: 44.20,
    isc: 14.22,
    imp: 13.12,
    tempCoeffVoc: -0.250,
    tempCoeffIsc: 0.037,
    tempCoeffPmax: -0.28,
    noct: 43,
    efficiency: 22.47,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 28.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE', 'PID'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Gulf Solar Technologies',
    enabled: true,
  },
  {
    id: 'trina-vertex-n-670',
    brand: 'Trina Solar',
    model: 'Vertex N TSM-670DE21M',
    cellType: 'topcon',
    power: 670,
    voc: 54.80,
    vmp: 47.50,
    isc: 15.08,
    imp: 14.11,
    tempCoeffVoc: -0.240,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.27,
    noct: 44,
    efficiency: 24.10,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE', 'PID'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Gulf Solar Technologies',
    enabled: true,
  },
  {
    id: 'trina-vertex-n-700',
    brand: 'Trina Solar',
    model: 'Vertex N TSM-700NpG20',
    cellType: 'topcon',
    power: 700,
    voc: 56.10,
    vmp: 48.50,
    isc: 15.40,
    imp: 14.43,
    tempCoeffVoc: -0.235,
    tempCoeffIsc: 0.035,
    tempCoeffPmax: -0.26,
    noct: 45,
    efficiency: 24.82,
    cells: 156,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 32.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE', 'PID'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Gulf Solar Technologies',
    enabled: true,
  },

  // ============================================================
  // JA SOLAR - DeepBlue Series
  // ============================================================
  {
    id: 'ja-deepblue3-445',
    brand: 'JA Solar',
    model: 'DeepBlue 3.0 JAM78S30-445/MR',
    cellType: 'mono-perc',
    power: 445,
    voc: 41.80,
    vmp: 35.10,
    isc: 13.45,
    imp: 12.68,
    tempCoeffVoc: -0.270,
    tempCoeffIsc: 0.040,
    tempCoeffPmax: -0.32,
    noct: 43,
    efficiency: 21.33,
    cells: 120,
    cellSize: 182,
    dimensions: { width: 1134, height: 1722 },
    weight: 21.5,
    seriesFuseRating: 20,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 25,
    warrantyProduct: 12,
    degradationYear1: 2.0,
    degradationYear25: 5.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Amir Energy Co.',
    enabled: true,
  },
  {
    id: 'ja-deepblue4-570',
    brand: 'JA Solar',
    model: 'DeepBlue 4.0 JAM78D42-570/LB',
    cellType: 'topcon',
    power: 570,
    voc: 51.80,
    vmp: 43.60,
    isc: 14.02,
    imp: 13.07,
    tempCoeffVoc: -0.255,
    tempCoeffIsc: 0.038,
    tempCoeffPmax: -0.29,
    noct: 43,
    efficiency: 22.05,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 28.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Amir Energy Co.',
    enabled: true,
  },
  {
    id: 'ja-deepblue4-630',
    brand: 'JA Solar',
    model: 'DeepBlue 4.0 JAM78D43-630/LB',
    cellType: 'topcon',
    power: 630,
    voc: 53.90,
    vmp: 46.00,
    isc: 14.60,
    imp: 13.70,
    tempCoeffVoc: -0.245,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.27,
    noct: 44,
    efficiency: 23.28,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Amir Energy Co.',
    enabled: true,
  },
  {
    id: 'ja-deepblue4-700-bf',
    brand: 'JA Solar',
    model: 'DeepBlue 4.0 700W Bifacial JAM78D40-700/LB',
    cellType: 'bifacial',
    power: 700,
    voc: 55.80,
    vmp: 48.20,
    isc: 15.38,
    imp: 14.52,
    tempCoeffVoc: -0.240,
    tempCoeffIsc: 0.035,
    tempCoeffPmax: -0.26,
    noct: 45,
    efficiency: 24.35,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 30.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'Transparent',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Amir Energy Co.',
    enabled: true,
  },

  // ============================================================
  // CANADIAN SOLAR - HiKu / BiHiKu Series
  // ============================================================
  {
    id: 'cs-topHiKu6-445',
    brand: 'Canadian Solar',
    model: 'TOPHiKu6 CS6R-445MS',
    cellType: 'topcon',
    power: 445,
    voc: 42.00,
    vmp: 35.30,
    isc: 13.50,
    imp: 12.61,
    tempCoeffVoc: -0.260,
    tempCoeffIsc: 0.038,
    tempCoeffPmax: -0.29,
    noct: 42,
    efficiency: 21.68,
    cells: 120,
    cellSize: 182,
    dimensions: { width: 1134, height: 1722 },
    weight: 21.8,
    seriesFuseRating: 20,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Hadhramaut Solar Distributors',
    enabled: true,
  },
  {
    id: 'cs-hiku7-580',
    brand: 'Canadian Solar',
    model: 'HiKu7 CS7N-580TB',
    cellType: 'mono-perc',
    power: 580,
    voc: 50.40,
    vmp: 42.80,
    isc: 14.75,
    imp: 13.55,
    tempCoeffVoc: -0.265,
    tempCoeffIsc: 0.040,
    tempCoeffPmax: -0.30,
    noct: 44,
    efficiency: 21.55,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 28.6,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 25,
    warrantyProduct: 12,
    degradationYear1: 2.0,
    degradationYear25: 5.0,
    availableInYemen: true,
    yemenDistributor: 'Hadhramaut Solar Distributors',
    enabled: true,
  },
  {
    id: 'cs-biHiKu7-645',
    brand: 'Canadian Solar',
    model: 'BiHiKu7 CS7W-645TB',
    cellType: 'bifacial',
    power: 645,
    voc: 53.80,
    vmp: 46.50,
    isc: 14.70,
    imp: 13.87,
    tempCoeffVoc: -0.250,
    tempCoeffIsc: 0.037,
    tempCoeffPmax: -0.28,
    noct: 44,
    efficiency: 23.30,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 30.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'Transparent',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Hadhramaut Solar Distributors',
    enabled: true,
  },
  {
    id: 'cs-biHiKu7-690',
    brand: 'Canadian Solar',
    model: 'BiHiKu7 CS7W-690MS',
    cellType: 'bifacial',
    power: 690,
    voc: 55.50,
    vmp: 48.00,
    isc: 15.20,
    imp: 14.38,
    tempCoeffVoc: -0.245,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.27,
    noct: 45,
    efficiency: 24.52,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 30.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'Transparent',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'UL', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Hadhramaut Solar Distributors',
    enabled: true,
  },

  // ============================================================
  // TW SOLAR (TONGWEI) - N-type TOPCon Series
  // ============================================================
  {
    id: 'tw-nf668hd',
    brand: 'TW Solar',
    model: 'TW-NF668HD',
    cellType: 'topcon',
    power: 668,
    voc: 54.60,
    vmp: 47.10,
    isc: 15.02,
    imp: 14.18,
    tempCoeffVoc: -0.240,
    tempCoeffIsc: 0.035,
    tempCoeffPmax: -0.26,
    noct: 44,
    efficiency: 24.18,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Sana\'a Solar Import',
    enabled: true,
  },
  {
    id: 'tw-nf728hd',
    brand: 'TW Solar',
    model: 'TW-NF728HD',
    cellType: 'topcon',
    power: 728,
    voc: 56.80,
    vmp: 49.20,
    isc: 15.62,
    imp: 14.80,
    tempCoeffVoc: -0.235,
    tempCoeffIsc: 0.035,
    tempCoeffPmax: -0.25,
    noct: 45,
    efficiency: 24.95,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Sana\'a Solar Import',
    enabled: true,
  },
  {
    id: 'tw-nf788hd',
    brand: 'TW Solar',
    model: 'TW-NF788HD',
    cellType: 'topcon',
    power: 788,
    voc: 58.50,
    vmp: 50.80,
    isc: 16.30,
    imp: 15.51,
    tempCoeffVoc: -0.230,
    tempCoeffIsc: 0.034,
    tempCoeffPmax: -0.25,
    noct: 45,
    efficiency: 25.20,
    cells: 156,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 32.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Sana\'a Solar Import',
    enabled: true,
  },
  {
    id: 'tw-nf848hd',
    brand: 'TW Solar',
    model: 'TW-NF848HD',
    cellType: 'topcon',
    power: 848,
    voc: 60.20,
    vmp: 52.50,
    isc: 17.05,
    imp: 16.15,
    tempCoeffVoc: -0.225,
    tempCoeffIsc: 0.034,
    tempCoeffPmax: -0.24,
    noct: 46,
    efficiency: 25.50,
    cells: 156,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Sana\'a Solar Import',
    enabled: true,
  },

  // ============================================================
  // ASTRONERGY (ASTRON POWER) - N-type TOPCon Series
  // ============================================================
  {
    id: 'astronergy-asd660h',
    brand: 'Astronergy',
    model: 'AS-D660H',
    cellType: 'topcon',
    power: 660,
    voc: 54.20,
    vmp: 46.80,
    isc: 14.95,
    imp: 14.10,
    tempCoeffVoc: -0.245,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 44,
    efficiency: 23.82,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 28.8,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Aden Solar Trade',
    enabled: true,
  },
  {
    id: 'astronergy-asd720h',
    brand: 'Astronergy',
    model: 'AS-D720H',
    cellType: 'topcon',
    power: 720,
    voc: 56.50,
    vmp: 49.00,
    isc: 15.55,
    imp: 14.69,
    tempCoeffVoc: -0.240,
    tempCoeffIsc: 0.035,
    tempCoeffPmax: -0.27,
    noct: 45,
    efficiency: 24.65,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 29.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Aden Solar Trade',
    enabled: true,
  },
  {
    id: 'astronergy-asd780h',
    brand: 'Astronergy',
    model: 'AS-D780H',
    cellType: 'topcon',
    power: 780,
    voc: 58.20,
    vmp: 50.50,
    isc: 16.20,
    imp: 15.45,
    tempCoeffVoc: -0.235,
    tempCoeffIsc: 0.034,
    tempCoeffPmax: -0.26,
    noct: 45,
    efficiency: 25.10,
    cells: 156,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 32.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Aden Solar Trade',
    enabled: true,
  },

  // ============================================================
  // LONGi SOLAR - Hi-MO 9 / Hi-MO X10 Series
  // ============================================================
  {
    id: 'longi-himo9-610w',
    brand: 'LONGi',
    model: 'Hi-MO 9 LR5-72HTH-610M',
    cellType: 'topcon',
    power: 610,
    voc: 49.20,
    vmp: 41.70,
    isc: 15.38,
    imp: 14.62,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 21.8,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'longi-himo9-630w',
    brand: 'LONGi',
    model: 'Hi-MO 9 LR5-72HTH-630M',
    cellType: 'topcon',
    power: 630,
    voc: 49.80,
    vmp: 42.50,
    isc: 15.65,
    imp: 14.82,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.5,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'longi-himox10-660w',
    brand: 'LONGi',
    model: 'Hi-MO X10 LR5-72HTH-660M',
    cellType: 'topcon',
    power: 660,
    voc: 50.50,
    vmp: 43.20,
    isc: 16.02,
    imp: 15.28,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.3,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'longi-himox10-680w',
    brand: 'LONGi',
    model: 'Hi-MO X10 LR5-72HTH-680M',
    cellType: 'topcon',
    power: 680,
    voc: 51.20,
    vmp: 43.80,
    isc: 16.25,
    imp: 15.53,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.8,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'longi-himox10-700w',
    brand: 'LONGi',
    model: 'Hi-MO X10 LR5-72HTH-700M',
    cellType: 'topcon',
    power: 700,
    voc: 51.80,
    vmp: 44.50,
    isc: 16.50,
    imp: 15.73,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 24.5,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // JA SOLAR - DeepBlue 4.0 Series
  // ============================================================
  {
    id: 'ja-deepblue4-700w',
    brand: 'JA Solar',
    model: 'DeepBlue 4.0 JAM78S30-700/MR',
    cellType: 'topcon',
    power: 700,
    voc: 53.60,
    vmp: 45.20,
    isc: 16.36,
    imp: 15.49,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.0,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'ja-deepblue4-720w',
    brand: 'JA Solar',
    model: 'DeepBlue 4.0 JAM78S30-720/MR',
    cellType: 'topcon',
    power: 720,
    voc: 54.20,
    vmp: 45.80,
    isc: 16.58,
    imp: 15.72,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.6,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // JINKO SOLAR - Tiger Neo High-Power Series
  // ============================================================
  {
    id: 'jinko-tiger-neo-670w',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM670N-72HL4-V',
    cellType: 'topcon',
    power: 670,
    voc: 51.50,
    vmp: 43.50,
    isc: 16.12,
    imp: 15.40,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.5,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'jinko-tiger-neo-700w2',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM700N-72HL4-V',
    cellType: 'topcon',
    power: 700,
    voc: 52.50,
    vmp: 44.20,
    isc: 16.50,
    imp: 15.84,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.8,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'jinko-tiger-neo-720w',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM720N-72HL4-V',
    cellType: 'topcon',
    power: 720,
    voc: 53.20,
    vmp: 44.80,
    isc: 16.72,
    imp: 16.07,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.3,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'jinko-tiger-neo-750w',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM750N-78HL4-V',
    cellType: 'topcon',
    power: 750,
    voc: 55.80,
    vmp: 46.50,
    isc: 17.10,
    imp: 16.13,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.8,
    cells: 156,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 35.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'jinko-tiger-neo-780w',
    brand: 'Jinko Solar',
    model: 'Tiger Neo JKM780N-78HL4-V',
    cellType: 'topcon',
    power: 780,
    voc: 56.50,
    vmp: 47.20,
    isc: 17.42,
    imp: 16.53,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 24.1,
    cells: 156,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 35.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // TRINA SOLAR - Vertex Series High-Power
  // ============================================================
  {
    id: 'trina-vertex-700w',
    brand: 'Trina Solar',
    model: 'Vertex S+ TSM-700RDG21',
    cellType: 'topcon',
    power: 700,
    voc: 53.10,
    vmp: 45.00,
    isc: 16.43,
    imp: 15.56,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.5,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'trina-vertexN-720w',
    brand: 'Trina Solar',
    model: 'Vertex N TSM-720NRD42',
    cellType: 'topcon',
    power: 720,
    voc: 53.80,
    vmp: 45.60,
    isc: 16.65,
    imp: 15.80,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.8,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'trina-vertexN-750w',
    brand: 'Trina Solar',
    model: 'Vertex N TSM-750NRD42',
    cellType: 'topcon',
    power: 750,
    voc: 55.20,
    vmp: 46.80,
    isc: 17.05,
    imp: 16.03,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.5,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 35.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // CANADIAN SOLAR - TOPHiKu7 Series
  // ============================================================
  {
    id: 'canadian-tophiku7-720w',
    brand: 'Canadian Solar',
    model: 'TOPHiKu7 CS7N-720TB',
    cellType: 'topcon',
    power: 720,
    voc: 53.50,
    vmp: 45.30,
    isc: 16.58,
    imp: 15.90,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.5,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'canadian-tophiku7-750w',
    brand: 'Canadian Solar',
    model: 'TOPHiKu7 CS7N-750TB',
    cellType: 'topcon',
    power: 750,
    voc: 54.80,
    vmp: 46.50,
    isc: 17.00,
    imp: 16.13,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.2,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'canadian-tophiku7-780w',
    brand: 'Canadian Solar',
    model: 'TOPHiKu7 CS7N-780TB',
    cellType: 'topcon',
    power: 780,
    voc: 55.90,
    vmp: 47.50,
    isc: 17.35,
    imp: 16.42,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.8,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.2,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // RISEN ENERGY - RSM40 Series
  // ============================================================
  {
    id: 'risen-rsm40-720w',
    brand: 'Risen Energy',
    model: 'RSM40-8-720M',
    cellType: 'topcon',
    power: 720,
    voc: 53.40,
    vmp: 45.10,
    isc: 16.60,
    imp: 15.96,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.4,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'risen-rsm40-750w',
    brand: 'Risen Energy',
    model: 'RSM40-8-750M',
    cellType: 'topcon',
    power: 750,
    voc: 54.60,
    vmp: 46.30,
    isc: 17.08,
    imp: 16.20,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.0,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // Q CELLS - Q.PEAK DUO Series
  // ============================================================
  {
    id: 'qcells-peak670',
    brand: 'Q Cells',
    model: 'Q.PEAK DUO L-G7.2 670',
    cellType: 'topcon',
    power: 670,
    voc: 51.20,
    vmp: 43.00,
    isc: 16.20,
    imp: 15.58,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 21.8,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 32.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'qcells-peak700',
    brand: 'Q Cells',
    model: 'Q.PEAK DUO L-G8.0 700',
    cellType: 'topcon',
    power: 700,
    voc: 52.80,
    vmp: 44.50,
    isc: 16.52,
    imp: 15.73,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.3,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2465 },
    weight: 33.5,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },

  // ============================================================
  // REC - Alpha Pure-R Series
  // ============================================================
  {
    id: 'rec-alpha700',
    brand: 'REC',
    model: 'Alpha Pure-R 700',
    cellType: 'topcon',
    power: 700,
    voc: 52.50,
    vmp: 44.20,
    isc: 16.50,
    imp: 15.84,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 22.5,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 33.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
  {
    id: 'rec-alpha720',
    brand: 'REC',
    model: 'Alpha Pure-R 720',
    cellType: 'topcon',
    power: 720,
    voc: 53.20,
    vmp: 45.00,
    isc: 16.72,
    imp: 16.00,
    tempCoeffVoc: -0.25,
    tempCoeffIsc: 0.036,
    tempCoeffPmax: -0.28,
    noct: 45,
    efficiency: 23.0,
    cells: 144,
    cellSize: 182,
    dimensions: { width: 1134, height: 2278 },
    weight: 33.0,
    seriesFuseRating: 25,
    maxSystemVoltage: 1500,
    frameColor: 'Silver',
    backsheetColor: 'White',
    certifications: ['IEC 61215', 'IEC 61730', 'TÜV', 'MCS', 'CE'],
    warrantyPerformance: 30,
    warrantyProduct: 15,
    degradationYear1: 1.0,
    degradationYear25: 2.0,
    availableInYemen: true,
    yemenDistributor: 'Al-Mansour Solar Solutions',
    enabled: true,
  },
];

export function getPanelsByBrand(brand: string): PanelDatabaseEntry[] {
  return yemenPanels.filter(
    (panel) => panel.brand.toLowerCase() === brand.toLowerCase() && panel.enabled
  );
}

export function getPanelsByPowerRange(minWatts: number, maxWatts: number): PanelDatabaseEntry[] {
  return yemenPanels.filter(
    (panel) => panel.power >= minWatts && panel.power <= maxWatts && panel.enabled
  );
}

export function getCompatiblePanels(
  minVoltage: number,
  maxVoltage: number,
  maxSeriesLength: number
): PanelDatabaseEntry[] {
  return yemenPanels.filter((panel) => {
    if (!panel.enabled) return false;
    const voltageOk = panel.voc <= maxVoltage && panel.vmp >= minVoltage;
    const lengthOk = panel.voc * maxSeriesLength <= maxVoltage;
    return voltageOk && lengthOk;
  });
}

export function searchPanels(query: string): PanelDatabaseEntry[] {
  const lowerQuery = query.toLowerCase();
  return yemenPanels.filter(
    (panel) =>
      panel.enabled &&
      (panel.brand.toLowerCase().includes(lowerQuery) ||
        panel.model.toLowerCase().includes(lowerQuery) ||
        panel.cellType.toLowerCase().includes(lowerQuery) ||
        panel.id.toLowerCase().includes(lowerQuery))
  );
}

export function getPanelById(id: string): PanelDatabaseEntry | undefined {
  return yemenPanels.find((panel) => panel.id === id);
}
